Small updates, rename user scripts directory.

diff --git a/update b/update
--- a/update
+++ b/update
@@ -3,11 +3,46 @@
 # Load source and destination paths
 source paths.sh
 
+BOLD_WHITE="\033[1;37m"
+BLUE="\033[34m"
+YELLOW="\033[33m"
+RED="\033[31m"
+ESC="\033[0m"
+
+# For every log function:
+#  $1: The log message
+#  $2: Escape characters added at the beginning of the log
+#  $3: Args passed to echo
+
+info()
+{
+	if [[ "$2" == *"\\r"* ]]; then
+        echo -en "\r\033[K"
+    fi
+	echo -e${3} "${2}${BOLD_WHITE}[${ESC}${BLUE}i${ESC}${BOLD_WHITE}]${ESC} ${1}" >&2
+}
+
+warning()
+{
+	if [[ "$2" == *"\\r"* ]]; then
+        echo -en "\r\033[K"
+    fi
+	echo -e${3} "${2}${BOLD_WHITE}[${ESC}${YELLOW}W${ESC}${BOLD_WHITE}]${ESC} ${1}" >&2
+}
+
+error()
+{
+	if [[ "$2" == *"\\r"* ]]; then
+        echo -en "\r\033[K"
+    fi
+	echo -e${3} "${2}${BOLD_WHITE}[${ESC}${RED}E${ESC}${BOLD_WHITE}]${ESC} ${1}" >&2
+}
+
 # Exits if the working directory is not in a git repo 
 ensure_in_git_repo()
 {
 	if ! git rev-parse --is-inside-work-tree &>/dev/null; then
-		echo "error: the script is not in a git repo."
+		error "Not in a git repo!"
 		exit 1
 	fi
 }
@@ -23,44 +58,69 @@ check_status()
 
 update()
 {
+	read -p "Do you want to overwrite the content of '$CONF/'? [y/N]: " choice
+	choice="${choice:-N}"
+	case "$choice" in
+		[Yy]* )
+			rm -rf "$CONF/"
+		;; [Nn]* )
+			info "ok."
+			exit 0
+		;; * )
+			error "Invalid input. Please answer with 'y' or 'n'."
+			exit 1
+		;;
+	esac
+
+	mkdir "$CONF/"
+
 	echo ""
 	echo "----------------"
 
 	echo -n "cava: "
+	mkdir -p "$CAVA_DST"
 	cp $CAVA_SRC $CAVA_DST/
 	check_status
 
 	echo -n "fastfetch: "
+	mkdir -p "$FASTFETCH_DST"
 	cp $FASTFETCH_SRC $FASTFETCH_DST/
 	check_status
 
 	echo -n "hypr: "
+	mkdir -p "$HYPR_DST"
 	cp -r $HYPR_SRC $HYPR_DST/
 	check_status
 
 	echo -n "mako: "
+	mkdir -p "$MAKO_DST"
 	cp $MAKO_SRC $MAKO_DST/
 	check_status
 
 	echo -n "scripts: "
+	mkdir -p "$SCRIPTS_DST"
 	cp -r $SCRIPTS_SRC* $SCRIPTS_DST
 	rm -rf $SCRIPTS_DST/theme-switcher/data/__pycache__/
 	rm -rf $SCRIPTS_DST/theme-switcher/tmp/
 	check_status
 
-	sudo bash -c "cp -r $SHARE_SRC/* $SHARE_DST; \
-		chown -R mikolaj *; \
-		if [ \$? -ne 0 ]; then echo 'share: error'; exit \$?; else echo 'share: ok'; fi"
+	echo -n "share:"
+	mkdir "$SHARE_DST"
+	cp -r $SHARE_SRC/* $SHARE_DST
+	check_status
 
 	echo -n "waybar: "
+	mkdir -p "$WAYBAR_DST"
 	cp $WAYBAR_SRC $WAYBAR_DST/
 	check_status
 
 	echo -n "wlogout: "
+	mkdir -p "$WLOGOUT_DST"
 	cp $WLOGOUT_SRC $WLOGOUT_DST/
 	check_status
 
 	echo -n "wofi: "
+	mkdir -p "$WOFI_DST"
 	cp $WOFI_SRC $WOFI_DST/
 	check_status
 
@@ -76,9 +136,9 @@ echo -e "\e[33mWARNING:\e[0m The script you are trying to execute is a utility m
 echo "To confirm please input the username of the owner of this repository:"
 read input
 
-if [ $input == "tpaau-17DB" ]; then
-	echo "Proceeding."
+if [[ "$input" == "tpaau-17DB" ]]; then
+	info "Proceeding."
 	update
 else
-	echo "Invalid input."
+	error "wrong"
 fi
